services:
  db:
    image: postgres:13
    container_name: postgres_conexean
    restart: always
    environment:
      POSTGRES_USER: conexean
      POSTGRES_PASSWORD: conexean
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
